<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CubicalCompare.Renderer</AssemblyName>
    <RootNamespace>CubicalCompare.Core.Renderer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\CubicalCompare.Core.csproj" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\CubicalCompare\Core\Renderer\**\*.cs" Link="Renderer\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
