using SkiaSharp;
using System.Text.RegularExpressions;

namespace CubicalCompare.Windows;

/// <summary>Windows/Skia port of Android InfiniteTimelineFrameRenderer. Logical canvas is 1920x1080.</summary>
public sealed class InfiniteTimelineRenderer : IDisposable
{
    private const int W = 1920, H = 1080;
    private const float OpeningPitch = 480, ConveyorPitch = 483, CardWidth = 474, TitleTop = 471, TitleBottom = 594, ArtTop = 732;
    private const float ScrollPerFrame = 3.2065854f, FastScrollPerFrame = 24;
    private const int FastScrollStart = 5265;
    private static readonly int[] DefaultOpening = [187, 261, 329, 398];
    private readonly Dictionary<string, SKBitmap> _images = new(StringComparer.OrdinalIgnoreCase);

    public SKBitmap Render(StudioProject project, RendererSpec spec, int frame, int width, int height)
    {
        width=Math.Max(2,width);height=Math.Max(2,height);var output=new SKBitmap(new SKImageInfo(width,height,SKColorType.Bgra8888,SKAlphaType.Premul));using var canvas=new SKCanvas(output);canvas.Scale(width/(float)W,height/(float)H);DrawReference(canvas,project,spec,Math.Max(0,frame));canvas.Flush();return output;
    }

    public int FrameCount(StudioProject project, RendererSpec spec)
    {
        if(!project.AutoLength)return Math.Max(1,(int)Math.Round(project.CustomLengthSeconds*Math.Max(1,spec.ReferenceFps)));
        if(project.Cards.Count==35&&spec.CanonicalFrameCount==5457)return 5457;
        var steps=Math.Max(0,project.Cards.Count-4);return spec.ContinuousStartFrame+(int)Math.Round(steps*StepFrames(project,spec))+205+(5457-5305);
    }
    private float StepFrames(StudioProject project,RendererSpec spec){if(project.AutoLength||project.Cards.Count<=4)return Math.Max(1,spec.ContinuousStepFrames);var target=(int)Math.Round(project.CustomLengthSeconds*Math.Max(1,project.Fps));var fixedPart=spec.ContinuousStartFrame+205+(5457-5305);var moving=Math.Max(project.Cards.Count-4,target-fixedPart);return moving/(float)Math.Max(1,project.Cards.Count-4);}
    private int OutroStart(StudioProject project,RendererSpec spec){if(project.AutoLength&&project.Cards.Count==35&&spec.CanonicalFrameCount==5457)return 5305;return spec.ContinuousStartFrame+(int)Math.Round(Math.Max(0,project.Cards.Count-4)*StepFrames(project,spec))+205;}

    private void DrawReference(SKCanvas canvas,StudioProject project,RendererSpec spec,int frame)
    {
        canvas.Clear(Background(spec,frame));if(frame<spec.ContinuousStartFrame){DrawBrandIntro(canvas,project,frame);DrawDisclaimer(canvas,project,frame);}if(project.Cards.Count==0)return;var outro=OutroStart(project,spec);if(frame<spec.ContinuousStartFrame)DrawOpening(canvas,project,spec,frame);else if(frame<outro)DrawConveyor(canvas,project,spec,frame);else DrawOutro(canvas,project,spec,frame,outro);
    }
    private SKColor Background(RendererSpec spec,int frame){if(frame<spec.ContinuousStartFrame)return Color(spec.BackgroundColor);var continuous=new SKColor(25,14,17);if(frame<5260)return continuous;var p=spec.Track("infinite.outro.bg.progress",frame)??Math.Clamp((frame-5260)/150f,0,1);var target=Color(spec.BackgroundColor);return LerpColor(continuous,target,p);}

    private void DrawBrandIntro(SKCanvas c,StudioProject p,int frame)
    {
        if(frame<12)return;var settle=frame<30?Sample([(12,8f),(18,7.4f),(24,6.5f),(30,5.7f)],frame):frame<90?Sample([(30,5.7f),(45,3.7f),(60,2.35f),(75,1.47f),(90,1f)],frame):1;var alpha=frame<16?Math.Clamp((frame-12)/4f,0,1):1;var cx=960f;var cy=466f;c.Save();c.Scale(settle,settle,cx,cy);DrawInfinity(c,cx,cy,alpha);c.Restore();if(frame>=128){var line1="Infinite";var line2="Comparison";var visible=Math.Clamp((int)((frame-128)*.76f),0,line1.Length+line2.Length);using var paint=TextPaint(p,35,new SKColor(220,214,214,(byte)(210*alpha)),false);paint.TextAlign=SKTextAlign.Center;var first=line1[..Math.Min(line1.Length,visible)];var second=visible>line1.Length?line2[..Math.Min(line2.Length,visible-line1.Length)]:"";if(first.Length>0)c.DrawText(first,cx,602,paint);if(second.Length>0)c.DrawText(second,cx,639,paint);}}
    private static void DrawInfinity(SKCanvas c,float cx,float cy,float alpha)
    {
        var left=new SKRect(cx-170,cy-84,cx+8,cy+84);var right=new SKRect(cx-8,cy-84,cx+170,cy+84);void Stroke(float width,SKColor color,float l=35,float r=215){using var p=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeCap=SKStrokeCap.Round,StrokeWidth=width,Color=new SKColor(color.Red,color.Green,color.Blue,(byte)(color.Alpha*alpha))};c.DrawArc(left,l,290,false,p);c.DrawArc(right,r,290,false,p);}Stroke(32,new SKColor(0,0,0,95));Stroke(22,new SKColor(24,24,24));using(var p=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeCap=SKStrokeCap.Round,StrokeWidth=11,Shader=SKShader.CreateLinearGradient(new SKPoint(cx-170,cy),new SKPoint(cx+170,cy),[new SKColor(204,235,20),SKColors.White,new SKColor(235,128,145)],[0,.5f,1],SKShaderTileMode.Clamp),Color=new SKColor(255,255,255,(byte)(255*alpha))}){c.DrawArc(left,35,290,false,p);c.DrawArc(right,215,290,false,p);}Stroke(4,new SKColor(240,240,240));using var lines=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeCap=SKStrokeCap.Round,StrokeWidth=5,Color=new SKColor(242,242,242,(byte)(235*alpha))};c.DrawLine(cx-100,cy-67,cx+100,cy+67,lines);c.DrawLine(cx+100,cy-67,cx-100,cy+67,lines);
    }
    private void DrawDisclaimer(SKCanvas c,StudioProject project,int frame){if(frame<222)return;var text="DISCLAIMER: This\ncomparison video\nis based on public\ndata, surveys,\npublic comments &\ndiscussions and\napproximate\nestimations that\nmight be subjected\nto some degree of\nerror.";using var paint=TextPaint(project,24,new SKColor(217,208,208),false);var y=659f;foreach(var line in text.Split('\n')){c.DrawText(line,1455,y,paint);y+=31;}}

    private void DrawOpening(SKCanvas c,StudioProject project,RendererSpec spec,int frame)
    {
        for(var i=0;i<Math.Min(4,project.Cards.Count);i++){var start=i<spec.OpeningStarts.Count?spec.OpeningStarts[i]:DefaultOpening[i];var local=frame-start;if(local<0)continue;var x=i*OpeningPitch;var scale=spec.Track("infinite.open.card.scale",local)??OpeningCardScale(local);if(scale>0){var cx=x+OpeningPitch/2;c.Save();c.Scale(scale,scale,cx,H/2f);DrawCard(c,project,project.Cards[i],x,spec,OpeningContent(spec,local),OpeningPitch);c.Restore();}var badgeLocal=local-5;if(badgeLocal>=0)DrawBadge(c,project,project.Cards[i],x,spec,spec.Track("infinite.open.badge.scale",badgeLocal)??OpeningBadgeScale(badgeLocal),badgeLocal);var wipe=OpeningContent(spec,local);if(wipe>0&&wipe<1)DrawWipe(c,x,wipe,OpeningPitch);}
    }
    private static float OpeningCardScale(int local)=>Math.Clamp(Sample([(0,.029514f),(1,.203125f),(2,.382639f),(3,.553125f),(4,.714583f),(5,.863194f),(6,.992361f),(7,1f)],local),0,1);
    private static float OpeningBadgeScale(int local)=>Math.Max(0,Sample([(0,.02046f),(1,.212275f),(2,.390203f),(3,.568506f),(4,.73292f),(5,.877799f),(6,1.006579f),(7,1.119403f),(8,1.19403f),(9,1.19403f),(10,1.119403f),(11,1.014407f),(12,.946657f),(13,.904092f),(14,.931494f),(15,.973329f),(16,1.026671f),(17,1.054054f),(18,1.041667f),(19,1.026671f),(20,1f)],local));
    private static float OpeningContent(RendererSpec spec,int local)=>Math.Clamp(spec.Track("infinite.open.content.wipe",local)??(local<31?0:local>=59?1:(local-31)/28f),0,1);
    private static void DrawWipe(SKCanvas c,float x,float p,float pitch){var y=H*Math.Clamp(p,0,1);using var paint=new SKPaint{Shader=SKShader.CreateLinearGradient(new SKPoint(0,y-58),new SKPoint(0,y+58),[SKColors.Transparent,new SKColor(255,255,255,28),new SKColor(255,255,255,120),new SKColor(255,255,255,28),SKColors.Transparent],[0,.28f,.5f,.72f,1],SKShaderTileMode.Clamp)};c.DrawRect(x,y-58,pitch,116,paint);}

    private void DrawConveyor(SKCanvas c,StudioProject project,RendererSpec spec,int frame)
    {
        var scroll=ConveyorScroll(spec,frame);var first=Math.Max(0,(int)Math.Floor(scroll/ConveyorPitch));var last=Math.Min(project.Cards.Count-1,first+4);for(var i=first;i<=last;i++){if(i<0||i>=project.Cards.Count)continue;var x=i*ConveyorPitch-scroll;if(x>=W||x+ConveyorPitch<=0)continue;var local=i<4?frame-(i<spec.OpeningStarts.Count?spec.OpeningStarts[i]:DefaultOpening[i]):int.MaxValue;var reveal=i<4?OpeningContent(spec,local):1;DrawCard(c,project,project.Cards[i],x,spec,reveal,ConveyorPitch);if(i<4){DrawBadge(c,project,project.Cards[i],x,spec,1,int.MaxValue);if(reveal>0&&reveal<1)DrawWipe(c,x,reveal,ConveyorPitch);}else DrawLaterBadge(c,project,project.Cards[i],x,spec,frame,i);}
    }
    private static float ConveyorScroll(RendererSpec spec,int frame){var exact=spec.Track("infinite.scroll",frame);if(exact!=null)return exact.Value;var normal=Math.Max(0,frame-spec.ContinuousStartFrame)*ScrollPerFrame;if(frame<=FastScrollStart)return normal;var atFast=Math.Max(0,FastScrollStart-spec.ContinuousStartFrame)*ScrollPerFrame;return atFast+(frame-FastScrollStart)*FastScrollPerFrame;}

    private void DrawCard(SKCanvas c,StudioProject project,StudioCard card,float x,RendererSpec spec,float reveal,float pitch)
    {
        var right=x+CardWidth;using var paint=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Fill};paint.Color=new SKColor(30,30,30);c.DrawRect(x,0,CardWidth,TitleTop,paint);paint.Color=Color(spec.TitleBackgroundColor);c.DrawRect(x,TitleTop,CardWidth,TitleBottom-TitleTop,paint);paint.Color=new SKColor(226,128,0);c.DrawRect(x,TitleBottom-6,CardWidth,6,paint);paint.Color=Color(spec.DescriptionBackgroundColor);c.DrawRect(x,TitleBottom,CardWidth,H-TitleBottom,paint);paint.Color=new SKColor(8,8,8);c.DrawRect(right,0,Math.Max(0,pitch-CardWidth),H,paint);var p=Math.Clamp(reveal,0,1);if(p<=0)return;c.Save();if(p<1)c.ClipRect(new SKRect(x,0,x+pitch,H*p));DrawWrapped(c,project,card.Title,new SKRect(x+9,TitleTop+2,right-9,TitleBottom-8),50,32,2,new SKColor(20,20,20),true,.93f);DrawWrapped(c,project,card.Description,new SKRect(x+12,TitleBottom+8,right-12,ArtTop-5),27,19,4,new SKColor(226,226,226),false,1.02f);DrawArtwork(c,card,new SKRect(x+9,ArtTop+3,right-9,H-3));c.Restore();
    }
    private void DrawArtwork(SKCanvas c,StudioCard card,SKRect dest){var bitmap=Load(card.Image);if(bitmap==null)return;var src=new SKRect((float)(bitmap.Width*Math.Clamp(card.ImageCropLeft,0,.95)),(float)(bitmap.Height*Math.Clamp(card.ImageCropTop,0,.95)),(float)(bitmap.Width*(1-Math.Clamp(card.ImageCropRight,0,.95))),(float)(bitmap.Height*(1-Math.Clamp(card.ImageCropBottom,0,.95))));if(src.Width<1||src.Height<1)return;var scale=Math.Min(dest.Width/src.Width,dest.Height/src.Height)*(float)Math.Clamp(card.ImageScale,.05,12);var dw=src.Width*scale;var dh=src.Height*scale;var cx=dest.MidX+(float)card.ImageX;var cy=dest.MidY+(float)card.ImageY;var target=new SKRect(cx-dw/2,cy-dh/2,cx+dw/2,cy+dh/2);c.Save();c.ClipRect(dest);if(card.ImageRotation!=0)c.RotateDegrees((float)card.ImageRotation,cx,cy);using var paint=new SKPaint{IsAntialias=true,FilterQuality=SKFilterQuality.High};c.DrawBitmap(bitmap,src,target,paint);c.Restore();}

    private static SKPath BadgePath(float x){var p=new SKPath();p.MoveTo(x+249,12);p.LineTo(x+417,96);p.LineTo(x+459,291);p.LineTo(x+339,441);p.LineTo(x+132,441);p.LineTo(x+18,297);p.LineTo(x+63,90);p.Close();return p;}
    private void DrawBadge(SKCanvas c,StudioProject project,StudioCard card,float x,RendererSpec spec,float scale,int local)
    {
        if(!project.ShowBadges||(string.IsNullOrWhiteSpace(card.Value)&&string.IsNullOrWhiteSpace(card.BadgeHeader)))return;var cx=x+240;c.Save();c.Scale(scale,scale,cx,240);using var path=BadgePath(x);using(var shadow=new SKPaint{IsAntialias=true,Color=new SKColor(0,0,0,90)}){c.Save();c.Translate(5,8);c.DrawPath(path,shadow);c.Restore();}using(var fill=new SKPaint{IsAntialias=true,Shader=SKShader.CreateLinearGradient(new SKPoint(0,10),new SKPoint(0,445),new SKColor[]{new SKColor(239,29,23),new SKColor(204,11,11)},new float[]{0f,1f},SKShaderTileMode.Clamp)})c.DrawPath(path,fill);using(var stroke=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeWidth=3,Color=new SKColor(194,194,184)})c.DrawPath(path,stroke);if(local==int.MaxValue)DrawBadgeText(c,project,card,cx,spec);else{var reveal=OpeningContent(spec,local+5);if(reveal>0){c.Save();c.ClipRect(new SKRect(x,0,x+OpeningPitch,H*reveal));DrawBadgeText(c,project,card,cx,spec);c.Restore();}}c.Restore();
    }
    private void DrawLaterBadge(SKCanvas c,StudioProject project,StudioCard card,float x,RendererSpec spec,int frame,int index)
    {
        if(!project.ShowBadges||(string.IsNullOrWhiteSpace(card.Value)&&string.IsNullOrWhiteSpace(card.BadgeHeader)))return;var first=spec.Track("infinite.later.firstStart",0)??602;var step=spec.Track("infinite.later.step",0)??150.62752f;var start=(int)Math.Floor(first+Math.Max(0,index-4)*step);var local=frame-start;if(local<0)return;var outline=Math.Max(1,spec.Track("infinite.later.outlineFrames",0)??20);var fillStart=Math.Max(outline,spec.Track("infinite.later.fillStart",0)??23);var settle=Math.Max(fillStart+1,spec.Track("infinite.later.settleFrames",0)??34);using var path=BadgePath(x);if(local<fillStart){var progress=Math.Clamp(local/outline,0,1);using var measure=new SKPathMeasure(path,true);using var partial=new SKPath();measure.GetSegment(0,measure.Length*progress,partial,true);using var pen=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeWidth=3,StrokeCap=SKStrokeCap.Round,StrokeJoin=SKStrokeJoin.Round,Color=new SKColor(160,176,151)};c.DrawPath(partial,pen);return;}var p=Math.Clamp((local-fillStart)/(settle-fillStart),0,1);var alpha=(byte)Math.Clamp((int)Math.Round(72+183*p),0,255);using(var fill=new SKPaint{IsAntialias=true,Color=new SKColor(Color(spec.BadgeColor).Red,Color(spec.BadgeColor).Green,Color(spec.BadgeColor).Blue,alpha)})c.DrawPath(path,fill);using(var stroke=new SKPaint{IsAntialias=true,Style=SKPaintStyle.Stroke,StrokeWidth=3,Color=new SKColor(194,194,184)})c.DrawPath(path,stroke);if(p>.08f){c.SaveLayer(new SKPaint{Color=new SKColor(255,255,255,(byte)(255*p))});DrawBadgeText(c,project,card,x+240,spec);c.Restore();}
    }
    private void DrawBadgeText(SKCanvas c,StudioProject project,StudioCard card,float cx,RendererSpec spec){var header=string.IsNullOrWhiteSpace(card.BadgeHeader)?"Before":card.BadgeHeader.Trim();var parts=Regex.Split(card.Value.Trim(),"\\s+",RegexOptions.CultureInvariant);var primary=parts.FirstOrDefault()??"";var unit=parts.Length>1?string.Join(' ',parts.Skip(1)):"";using var paint=TextPaint(project,57,Color(spec.BadgeTextColor),false);DrawCentered(c,header,cx,128,paint,30,380);DrawCentered(c,primary,cx,256,paint,58,330);if(unit.Length>0)DrawCentered(c,unit,cx,360,paint,32,360);}

    private void DrawOutro(SKCanvas c,StudioProject project,RendererSpec spec,int frame,int outroStart)
    {
        var last=project.Cards[^1];var sx=(spec.Track("infinite.outro.card.x",frame)?.Div(3))??Sample([(5305,4f),(5310,100f),(5315,240f),(5320,318f),(5325,262f),(5330,206f),(5335,224f),(5340,260f),(5345,268f),(5350,264f),(5355,266f),(5360,268f),(5370,266f)],frame);var x=sx*3;DrawCard(c,project,last,x,spec,1,ConveyorPitch);DrawBadge(c,project,last,x,spec,1,int.MaxValue);var message="Although it seems impossible there are quite a few people who have swallowed their phone.";var start=(int)Math.Round(spec.Track("infinite.outro.message.start",0)??5310);var chars=Math.Clamp(frame-start,0,message.Length);if(chars>0)DrawTypedParagraph(c,project,message[..chars],new SKRect(24,240,750,585),45,SKColors.White);var subStart=(int)Math.Round(spec.Track("infinite.outro.subscribe.start",0)??5407);if(frame>=subStart){var visible=Math.Max(0,frame-subStart);var subscribe="Subscribe";using var p=TextPaint(project,48,new SKColor(224,132,15),false);var a=subscribe[..Math.Min(subscribe.Length,visible)];c.DrawText(a,24,780,p);if(visible>subscribe.Length){p.Color=new SKColor(242,242,242);var rest=" for more\ncomparison videos.";var rv=rest[..Math.Min(rest.Length,visible-subscribe.Length)];var first=rv.Split('\n')[0];c.DrawText(first,24+p.MeasureText(subscribe),780,p);if(rv.Contains('\n'))c.DrawText(rv[(rv.IndexOf('\n')+1)..],24,837,p);}}}

    private static void DrawTypedParagraph(SKCanvas c,StudioProject project,string text,SKRect box,float size,SKColor color){using var paint=TextPaint(project,size,color,false);var lines=Wrap(text,paint,box.Width);var y=box.Top+size;foreach(var line in lines){c.DrawText(line,box.Left,y,paint);y+=size*1.08f;}}
    private static void DrawWrapped(SKCanvas c,StudioProject project,string text,SKRect box,float preferred,float minimum,int maxLines,SKColor color,bool bold,float factor){if(string.IsNullOrWhiteSpace(text))return;using var paint=TextPaint(project,preferred,color,bold);var size=preferred;List<string> lines=[];while(true){paint.TextSize=size;lines=Wrap(Regex.Replace(text,"\\s+"," "),paint,box.Width);if((lines.Count<=maxLines&&lines.Count*size*factor<=box.Height)||size<=minimum)break;size--;}paint.TextAlign=SKTextAlign.Center;paint.TextSize=size;var lineH=size*factor;var y=box.MidY-lines.Count*lineH/2+lineH/2;foreach(var line in lines.Take(maxLines)){var metrics=paint.FontMetrics;c.DrawText(line,box.MidX,y-(metrics.Ascent+metrics.Descent)/2,paint);y+=lineH;}}
    private static List<string> Wrap(string text,SKPaint paint,float width){var lines=new List<string>();var current="";foreach(var word in text.Split(' ',StringSplitOptions.RemoveEmptyEntries)){var candidate=current.Length==0?word:current+" "+word;if(current.Length==0||paint.MeasureText(candidate)<=width)current=candidate;else{lines.Add(current);current=word;}}if(current.Length>0)lines.Add(current);return lines;}
    private static void DrawCentered(SKCanvas c,string text,float x,float y,SKPaint paint,float min,float maxWidth){if(string.IsNullOrWhiteSpace(text))return;var preferred=paint.TextSize;while(paint.MeasureText(text)>maxWidth&&paint.TextSize>min)paint.TextSize--;paint.TextAlign=SKTextAlign.Center;var metrics=paint.FontMetrics;c.DrawText(text,x,y-(metrics.Ascent+metrics.Descent)/2,paint);paint.TextSize=preferred;paint.TextAlign=SKTextAlign.Left;}
    private static SKPaint TextPaint(StudioProject project,float size,SKColor color,bool bold){SKTypeface face;try{face=!string.IsNullOrWhiteSpace(project.FontFile)&&File.Exists(project.FontFile)?SKTypeface.FromFile(project.FontFile):SKTypeface.FromFamilyName(string.IsNullOrWhiteSpace(project.FontFamily)?"Segoe UI":project.FontFamily,bold?SKFontStyle.Bold:SKFontStyle.Normal);}catch{face=SKTypeface.Default;}return new SKPaint{IsAntialias=true,SubpixelText=true,Typeface=face,TextSize=size,Color=color};}
    private SKBitmap? Load(string path){if(string.IsNullOrWhiteSpace(path)||path.StartsWith("http://",StringComparison.OrdinalIgnoreCase)||path.StartsWith("https://",StringComparison.OrdinalIgnoreCase)||!File.Exists(path))return null;if(_images.TryGetValue(path,out var hit))return hit;try{var b=SKBitmap.Decode(path);if(b!=null)_images[path]=b;return b;}catch{return null;}}
    private static float Sample((int Frame,float Value)[] keys,int frame){if(frame<=keys[0].Frame)return keys[0].Value;if(frame>=keys[^1].Frame)return keys[^1].Value;for(var i=1;i<keys.Length;i++){var r=keys[i];if(frame<=r.Frame){var l=keys[i-1];var p=(frame-l.Frame)/(float)Math.Max(1,r.Frame-l.Frame);return l.Value+(r.Value-l.Value)*p;}}return keys[^1].Value;}
    private static SKColor Color(uint argb)=>new((byte)(argb>>16),(byte)(argb>>8),(byte)argb,(byte)(argb>>24));
    private static SKColor LerpColor(SKColor a,SKColor b,float p){p=Math.Clamp(p,0,1);return new SKColor((byte)Math.Round(a.Red+(b.Red-a.Red)*p),(byte)Math.Round(a.Green+(b.Green-a.Green)*p),(byte)Math.Round(a.Blue+(b.Blue-a.Blue)*p),(byte)Math.Round(a.Alpha+(b.Alpha-a.Alpha)*p));}
    public void Dispose(){foreach(var image in _images.Values.Distinct())image.Dispose();_images.Clear();}
}

internal static class FloatExtensions { public static float Div(this float value,float divisor)=>value/divisor; }
